/* js/pdf.js — document and report download generators */

function downloadTrustDocument(S) {
  if (!S.generatedDoc) return;
  const g    = S.g;
  const sn   = SA[g.state?.toUpperCase()] || g.state || '—';
  const date = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  const html = `<!DOCTYPE html>
<html lang="en"><head>
<meta charset="UTF-8">
<title>${g.tname || 'Trust Framework'}</title>
<style>
  body { font-family: Georgia, serif; max-width: 760px; margin: 50px auto; padding: 0 40px; color: #1a1a1a; font-size: 14px; line-height: 1.9; }
  h1   { font-size: 18px; text-align: center; text-transform: uppercase; letter-spacing: .1em; margin-bottom: 4px; }
  .sub { text-align: center; font-size: 12px; color: #666; margin-bottom: 24px; }
  .notice { background: #f5f5f0; border: 1px solid #ccc; padding: 14px 18px; border-radius: 4px; font-size: 12px; margin-bottom: 32px; line-height: 1.7; }
  pre  { white-space: pre-wrap; font-family: Georgia, serif; font-size: 14px; line-height: 1.9; }
  .footer { margin-top: 52px; padding-top: 14px; border-top: 1px solid #ccc; font-size: 11px; color: #999; }
</style>
</head><body>
<h1>${g.tname || 'Trust Framework Document'}</h1>
<div class="sub">${sn} &nbsp;·&nbsp; ${date} &nbsp;·&nbsp; Pro Se Framework &nbsp;·&nbsp; Rockefeller Blueprint</div>
<div class="notice">
  <strong>PRO SE TRUST FRAMEWORK — WORKING DRAFT</strong><br>
  This is a private instrument drafted by the grantor under 28 U.S.C. § 1654 and the right
  affirmed in <em>Faretta v. California</em>, 422 U.S. 806 (1975). A trust is a private document
  between private parties. It does not require filing with any court or government office. It is
  presented as needed to financial institutions, tax advisors, and attorneys.<br><br>
  <strong>Professional review by a licensed estate attorney and CPA is strongly encouraged before
  execution, witnessing, and notarization.</strong> Signature and notarization requirements vary by state.
</div>
<pre>${(S.generatedDoc || '').replace(/[<>]/g, ' ')}</pre>
<div class="footer">
  Generated by Trust Doctor · Rockefeller Blueprint Edition · ${date}<br>
  Working draft. Not legal advice. Professional review strongly encouraged before execution.
</div>
</body></html>`;

  downloadBlob(html, `${(g.tname || 'TrustFramework').replace(/\s+/g, '_')}.html`);
  showToast('Document downloaded');
}

function downloadFullReport(S) {
  const g    = S.g;
  const sn   = SA[g.state?.toUpperCase()] || g.state || '—';
  const date = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  const nl   = S.needs.map(id => NEEDS.find(n => n.id === id)?.l || id).join(', ');
  const ps   = S.parties.map(p => `${p.r}: ${p.n}`).join(' | ') || 'None';
  const sc   = S.scores || {};
  const tot  = PILLARS.map(p => sc[p.id] || 0).reduce((a, v) => a + v, 0);
  const pct  = Math.round((tot / (PILLARS.length * 10)) * 100);
  const fc   = familyComplexity(S.parties);

  const docSec = S.docAnalysis
    ? `<h2>Document review results</h2>
       <div class="sec">
         <h3>Gaps identified:</h3>
         <ul>${(S.docAnalysis.gaps || []).map(g =>
           `<li><strong>[${g.sev}]</strong> ${g.title}: ${g.body}</li>`).join('')}</ul>
         <h3>Strengths:</h3>
         <ul>${(S.docAnalysis.strengths || []).map(s =>
           `<li><strong>${s.title}</strong>: ${s.body}</li>`).join('')}</ul>
         <h3>Recommended improvements:</h3>
         <ul>${(S.docAnalysis.improvements || []).map((im, i) =>
           `<li><strong>${i + 1}. ${im.title}</strong>: ${im.body}</li>`).join('')}</ul>
       </div>`
    : '';

  const html = `<!DOCTYPE html>
<html lang="en"><head>
<meta charset="UTF-8">
<title>Rockefeller Blueprint Report — ${g.name}</title>
<style>
  body  { font-family: Georgia, serif; max-width: 720px; margin: 40px auto; padding: 0 36px; color: #1a1a1a; font-size: 14px; line-height: 1.75; }
  h1    { font-size: 24px; border-bottom: 3px solid #1D9E75; padding-bottom: 10px; }
  h2    { font-size: 15px; font-weight: 700; margin-top: 28px; color: #0d3d2a; border-left: 4px solid #1D9E75; padding-left: 10px; }
  h3    { font-size: 13px; font-weight: 700; margin-top: 14px; color: #333; }
  .sec  { background: #f7f7f5; padding: 12px 16px; margin: 8px 0; border-radius: 6px; border-left: 3px solid #1D9E75; }
  .warn { background: #fff0f0; padding: 12px 16px; margin: 8px 0; border-radius: 6px; border-left: 3px solid #E24B4A; }
  pre   { white-space: pre-wrap; font-size: 13px; font-family: Georgia, serif; }
  ul    { padding-left: 1.5rem; }
  li    { margin-bottom: 6px; font-size: 13px; line-height: 1.6; }
  .footer { margin-top: 52px; padding-top: 14px; border-top: 1px solid #ccc; font-size: 11px; color: #999; }
</style>
</head><body>

<h1>Rockefeller Blueprint Trust Report</h1>
<p style="color:#666;font-size:13px">${date} &nbsp;·&nbsp; ${g.name || '—'} &nbsp;·&nbsp; ${sn} &nbsp;·&nbsp; ${g.tname || 'Unnamed Trust'}</p>

<h2>Pro se notice</h2>
<div class="sec">
  <p>Prepared by the grantor exercising rights under 28 U.S.C. § 1654 and
  <em>Faretta v. California</em>, 422 U.S. 806 (1975). A trust is a private document between
  private parties and does not require court filing or public recording. Professional review
  by a licensed estate attorney and CPA is strongly encouraged before execution.</p>
</div>

<h2>Grantor profile</h2>
<div class="sec">
  <p>
    Estate: ${g.ev || '—'} &nbsp;·&nbsp; Family profile: ${fc}<br>
    Goals: ${nl}<br>
    Parties: ${ps}<br>
    Assets: ${S.assets || '—'}<br>
    Circumstances: ${S.custom || '—'}
  </p>
</div>

${S.stateLaw
  ? `<h2>${sn} trust law</h2><div class="sec"><pre>${S.stateLaw}</pre></div>`
  : ''}

<h2>Rockefeller blueprint score: ${pct}%</h2>
<div class="sec">
  <ul>${PILLARS.map(p => `<li>${p.ic} ${p.l}: ${sc[p.id] || 0}/10</li>`).join('')}</ul>
  ${sc.insight ? `<p style="margin-top:8px;font-style:italic">${sc.insight}</p>` : ''}
</div>

<h2>Recommendations</h2>
<div class="sec"><pre>${(S.rec || '—').replace(/[<>]/g, ' ')}</pre></div>

${S.warns?.length
  ? `<h2>IRS compliance review</h2>
     <div class="warn">${S.warns.map(w =>
       `<p><strong>⚠ ${w.title}</strong>: ${w.body}</p>`).join('')}
     </div>`
  : ''}

${docSec}

${S.generatedDoc
  ? `<h2>Trust framework document</h2>
     <div class="sec"><pre>${S.generatedDoc.replace(/[<>]/g, ' ')}</pre></div>`
  : ''}

<h2>IRS reference resources</h2>
<div class="sec">
  <ul>
    <li><a href="https://www.irs.gov/businesses/small-businesses-self-employed/abusive-trust-tax-evasion-schemes-special-types-of-trusts">Trust tax compliance</a></li>
    <li><a href="https://www.irs.gov/charities-non-profits/charitable-organizations/private-foundations">Private foundations</a></li>
    <li><a href="https://www.irs.gov/charities-non-profits/exempt-organization-types">Exempt organization types</a></li>
    <li><a href="https://www.irs.gov/charities-non-profits/other-nonprofits">Other nonprofits</a></li>
    <li><a href="https://www.irs.gov/pub/irs-pdf/i990pf.pdf">Form 990-PF instructions</a></li>
  </ul>
</div>

<div class="footer">
  Trust Doctor &nbsp;·&nbsp; Rockefeller Blueprint Edition &nbsp;·&nbsp; ${date}<br>
  Working draft. Not legal advice. Professional review strongly encouraged before execution.
</div>
</body></html>`;

  downloadBlob(html, `RockefellerReport_${(g.name || 'Report').replace(/\s+/g, '_')}.html`);
  showToast('Report downloaded');
}

/* ─── Utility ─────────────────────────────────────────────────────────── */
function downloadBlob(content, filename) {
  const blob = new Blob([content], { type: 'text/html' });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement('a');
  a.href     = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
