const { Resend } = require('resend');

function getResendClient() {
  const key = process.env.RESEND_API_KEY;
  if (!key) throw new Error('RESEND_API_KEY not configured.');
  return new Resend(key);
}

function buildDocHtml(docContent, trustName, date) {
  const escaped = (docContent || '').replace(/[<>]/g, ' ');
  return `<!DOCTYPE html>
<html lang="en"><head>
<meta charset="UTF-8">
<title>${trustName || 'Trust Framework'}</title>
<style>
  body { font-family: Georgia, serif; max-width: 760px; margin: 50px auto; padding: 0 40px; color: #1a1a1a; font-size: 14px; line-height: 1.9; }
  h1   { font-size: 18px; text-align: center; text-transform: uppercase; letter-spacing: .1em; margin-bottom: 4px; }
  .sub { text-align: center; font-size: 12px; color: #666; margin-bottom: 24px; }
  .notice { background: #f5f5f0; border: 1px solid #ccc; padding: 14px 18px; border-radius: 4px; font-size: 12px; margin-bottom: 32px; line-height: 1.7; }
  pre  { white-space: pre-wrap; font-family: Georgia, serif; font-size: 14px; line-height: 1.9; }
  .footer { margin-top: 52px; padding-top: 14px; border-top: 1px solid #ccc; font-size: 11px; color: #999; }
</style>
</head><body>
<h1>${trustName || 'Trust Framework Document'}</h1>
<div class="sub">Pro Se Framework &nbsp;·&nbsp; Rockefeller Blueprint &nbsp;·&nbsp; ${date}</div>
<div class="notice">
  <strong>PRO SE TRUST FRAMEWORK — WORKING DRAFT</strong><br>
  This is a private instrument drafted by the grantor under 28 U.S.C. § 1654 and the right
  affirmed in <em>Faretta v. California</em>, 422 U.S. 806 (1975). A trust is a private document
  between private parties. It does not require filing with any court or government office.<br><br>
  <strong>Professional review by a licensed estate attorney and CPA is strongly encouraged before
  execution, witnessing, and notarization.</strong>
</div>
<pre>${escaped}</pre>
<div class="footer">
  Generated by Trust Doctor · Rockefeller Blueprint Edition · ${date}<br>
  Working draft. Not legal advice. Professional review strongly encouraged before execution.
</div>
</body></html>`;
}

function buildReceiptHtml(trustName, date) {
  return `<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8">
<style>
  body { font-family: -apple-system, sans-serif; background: #f9f9f7; margin: 0; padding: 40px 20px; }
  .card { background: white; border-radius: 12px; max-width: 520px; margin: 0 auto; padding: 40px; box-shadow: 0 2px 12px rgba(0,0,0,.08); }
  .check { width: 52px; height: 52px; border-radius: 50%; background: #2d6a4f; color: white; font-size: 22px; font-weight: 700; display: flex; align-items: center; justify-content: center; margin: 0 auto 20px; }
  h1 { font-size: 22px; text-align: center; color: #1a1a1a; margin: 0 0 8px; }
  .sub { text-align: center; color: #666; font-size: 14px; margin-bottom: 28px; }
  .row { display: flex; justify-content: space-between; padding: 10px 0; border-bottom: 1px solid #f0f0ec; font-size: 14px; }
  .row:last-of-type { border: none; }
  .label { color: #888; }
  .value { color: #1a1a1a; font-weight: 500; }
  .note { background: #f5f5f2; border-radius: 8px; padding: 14px 16px; font-size: 12px; color: #666; line-height: 1.65; margin: 24px 0 0; }
  .footer { text-align: center; font-size: 11px; color: #bbb; margin-top: 28px; }
</style>
</head><body>
<div class="card">
  <div style="text-align:center">
    <div class="check" style="display:inline-flex">✓</div>
  </div>
  <h1>Payment confirmed</h1>
  <p class="sub">Your full trust framework document is attached to this email.</p>
  <div class="row"><span class="label">Document</span><span class="value">${trustName || 'Trust Framework'}</span></div>
  <div class="row"><span class="label">Amount</span><span class="value">$19.00</span></div>
  <div class="row"><span class="label">Date</span><span class="value">${date}</span></div>
  <div class="row"><span class="label">Attachment</span><span class="value">${(trustName || 'TrustFramework').replace(/\s+/g, '_')}.html</span></div>
  <div class="note">
    <strong>What to do next:</strong> Open the attached .html file in any browser and use your browser's Print function to save it as a PDF, or print it directly. Have a licensed estate attorney review the document before signing, witnessing, and notarizing.
  </div>
  <p class="footer">Trust Doctor · Rockefeller Blueprint Edition<br>This is a receipt for your records. Please retain it.</p>
</div>
</body></html>`;
}

const OWNER_BCC = 'ai.solutions.serv@mail.com';

async function sendDocumentEmail({ toEmail, trustName, docContent }) {
  const resend = getResendClient();
  const date   = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  const filename = `${(trustName || 'TrustFramework').replace(/\s+/g, '_')}.html`;

  const docHtml  = buildDocHtml(docContent, trustName, date);
  const bodyHtml = buildReceiptHtml(trustName, date);

  const result = await resend.emails.send({
    from:    'Trust Doctor <onboarding@resend.dev>',
    to:      [toEmail],
    bcc:     [OWNER_BCC],
    subject: `Your Trust Framework Document — ${trustName || 'Trust Doctor'}`,
    html:    bodyHtml,
    attachments: [
      {
        filename,
        content: Buffer.from(docHtml).toString('base64'),
      }
    ]
  });

  return result;
}

module.exports = { sendDocumentEmail };
